### ISSUE TITLE
Include safe implementation of 'TarFile.extract'

### ISSUE THREAD

**Issue by mschwager** [beatsbears/tarsafe#2]
The `TarFile.extract` function has the same issue as `extractall`: https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extract

It'd be helpful to include a safe implementation of this function as well.

**Comment by beatsbears** [comment]
Thanks for the issue @mschwager, this has been addressed in #3 and should be available from pypi in v0.0.2
